### ISSUE TITLE
Active Deploy unmaps route of wrong app

### ISSUE THREAD

**Issue by jesusmah** [Osthanes/activedeploy_common#6]
@ptaube 
The Active Deploy - Begin deployer type scripts in for the delivery pipelines for containers unmaps the route of a wrong app. I have two apps: appetizers and desserts and if I map the route used for the dessert app to the appetizer app, the AD - Begin script will consider the appetizer app as an older version of the dessert app when I kick off the dessert delivery pipeline. It does so because the script looks at apps mapped with dessert's route without considering the PATTERN (as it appropriately does in the rampdown for deleting apps). As a result, the appetizer app will get its route unmapped. Also, the appetizer app is used for naming the AD instance as well as the original_gr_id.

I believe that a user should be able to use a common route for different apps and yet AD should upgrade apps appropriately without unmapping the route of any of them when a delivery pipeline for one of the apps is kicked off.

Please have a look at the log and specially to the bold text:

++ **logDebug 'wfd-dessert-ic-ad-1479989940988.mybluemix.net is routed to wfd-dessert-ic-ad_4' wfd-appetizer-ic-ad_2**
++ [[ -n 3 ]]
++ [[ 3 -ge 4 ]]
++ echo wfd-dessert-ic-ad_4 wfd-appetizer-ic-ad_2
+ **logDebug 2 of original groups routed to wfd-dessert-ic-ad-1479989940988.mybluemix.net: wfd-dessert-ic-ad_4 wfd-appetizer-ic-ad_2**
+ [[ -n 3 ]]
+ [[ 3 -ge 4 ]]
+ ((  1 < 2  ))
+ logWarning 'More than one app routed to wfd-dessert-ic-ad-1479989940988.mybluemix.net; **updating the oldest**'
+ [[ -n 3 ]]
+ [[ 3 -ge 2 ]]
+ echo -e '\e[0;33m--- WARNING: More than one app routed to wfd-dessert-ic-ad-1479989940988.mybluemix.net; updating the oldest\e[0m'
--- WARNING: More than one app routed to wfd-dessert-ic-ad-1479989940988.mybluemix.net; updating the oldest
+ ((  0 < 2  ))
+ readarray -t srtd
++ for e in '"${ROUTED[@]}"'
++ echo wfd-dessert-ic-ad_4
++ for e in '"${ROUTED[@]}"'
++ echo wfd-appetizer-ic-ad_2
++ sort
+ **original_grp=wfd-appetizer-ic-ad_2
+ original_grp_id=2
+ logDebug 'Original_grp: wfd-appetizer-ic-ad_2 - Original_grp_id: 2'**
+ [[ -n 3 ]]
+ [[ 3 -ge 4 ]]
+ [[ 1 = 7 ]]
+ [[ -z wfd-appetizer-ic-ad_2 ]]
+ logInfo 'Not initial version'
+ [[ -n 3 ]]
+ [[ 3 -ge 3 ]]
+ echo -e '\e[0;37m--- INFO: Not initial version\e[0m'
--- INFO: Not initial version
+ [[ -n '' ]]
+ **successor_grp=wfd-dessert-ic-ad_5
+ logDebug 'Original group is wfd-appetizer-ic-ad_2 (2)'**
+ [[ -n 3 ]]
+ [[ 3 -ge 4 ]]
+ logDebug 'Successor group is wfd-dessert-ic-ad_5 (5)'
+ [[ -n 3 ]]
+ [[ 3 -ge 4 ]]
+ [[ -n wfd-appetizer-ic-ad_2 ]]
+ [[ mybluemix.net == mybluemix.net ]]
+ logInfo 'ROUTE_DOMAIN is: mybluemix.net'
+ [[ -n 3 ]]
+ [[ 3 -ge 3 ]]
+ echo -e '\e[0;37m--- INFO: ROUTE_DOMAIN is: mybluemix.net\e[0m'
--- INFO: ROUTE_DOMAIN is: mybluemix.net
+ logInfo 'check if AD instance exists with cf services, if not create it.'
+ [[ -n 3 ]]
+ [[ 3 -ge 3 ]]
+ echo -e '\e[0;37m--- INFO: check if AD instance exists with cf services, if not create it.\e[0m'
--- INFO: check if AD instance exists with cf services, if not create it.
+ cf services
+ grep activedeploy
++ cat mp.output
+ foundservice='wfd_Active_Deploy            activedeploy          free                                                        update succeeded'
+ [[ -z wfd_Active_Deploy            activedeploy          free                                                        update succeeded ]]
+ logInfo 'Found Active Deploy Instance: activedeploy-for-pipeline'
+ [[ -n 3 ]]
+ [[ 3 -ge 3 ]]
+ echo -e '\e[0;37m--- INFO: Found Active Deploy Instance: activedeploy-for-pipeline\e[0m'
--- INFO: Found Active Deploy Instance: activedeploy-for-pipeline
+ logInfo 'Beginning update with cf active-deploy-create ...'
+ [[ -n 3 ]]
+ [[ 3 -ge 3 ]]
+ echo -e '\e[0;37m--- INFO: Beginning update with cf active-deploy-create ...\e[0m'
--- INFO: Beginning update with cf active-deploy-create ...
+ **create_args='wfd-appetizer-ic-ad_2 wfd-dessert-ic-ad_5** --manual --quiet --timeout 60s'
+ [[ -n 1s ]]
+ create_args='wfd-appetizer-ic-ad_2 wfd-dessert-ic-ad_5 --manual --quiet --timeout 60s --rampup 1s'

Thanks

**Comment by ptaube** [comment]
Thank you very much for reporting this issue. I just found the root cause and will create a fix.

**Comment by ptaube** [comment]
@jesusmah 
There is a fix available for you in the staging repo https://github.com/IBMActiveDeploy-Toolchain/update_service for the issue.

In order to use the staging repos instead of the Osthanes production repo please execute following steps:
1. Open the deploy stage in your pipeline and in configure stage execute:
   1. Create an environment variable called GIT_HOME and set it to IBMActiveDeploy-Toolchain
   2. Create an environment variable called LOG_LEVEL and set it to 4
2. Open the Active Deploy Start job and change the name of the repository used from Osthanes to IBMActiveDeploy-Toolchain (See below)
3. Open the Active Deploy Complete job and change the name of the repository used from Osthanes to IBMActiveDeploy-Toolchain (See below)
4. Start the toolchain and verify the fix

Change for ActiveDeploy Start:

```
source ${EXT_DIR}/git_util.sh
git_retry clone https://github.com/IBMActiveDeploy-Toolchain/update_service.git activedeploy
activedeploy/activedeploy_step_1.sh
```

Change for ActiveDeploy Complete:

```
source ${EXT_DIR}/git_util.sh
git_retry clone https://github.com/IBMActiveDeploy-Toolchain/update_service.git activedeploy
activedeploy/activedeploy_step_2.sh
```

Please test the fix and let me know your test results.

**Comment by jesusmah** [comment]
Fix seems to work. Thanks

**Comment by ptaube** [comment]
Thank you very much for testing and verifying the fix. I just merged the fix into the Osthanes repository and now the fix is active in production.
